---
apiVersion: kubeadm.k8s.io/v1beta3
kind: JoinConfiguration
discovery:
  bootstrapToken:
    apiServerEndpoint: $(MASTER_IP):6443
    token: acd5cb.gq1051m1py7t903k
    unsafeSkipCAVerification: true
  timeout: 5m0s
nodeRegistration:
  kubeletExtraArgs:
    node-ip: $(CONTROL_PLANE_IP)
  taints: []