---
apiVersion: kubeadm.k8s.io/v1beta3
kind: InitConfiguration
bootstrapTokens:
- groups:
  - system:bootstrappers:kubeadm:default-node-token
  token: acd5cb.gq1051m1py7t903k
  ttl: 2h0m0s
  usages:
  - signing
  - authentication
nodeRegistration:
  kubeletExtraArgs:
    node-ip: 192.168.0.2
  taints: []
localAPIEndpoint:
  advertiseAddress: 192.168.0.2
certificateKey: 4c47d3d9db10079c0e277cb809c3fdba278c4aa76f7e099b86cc9d23bdba1e37
---
apiVersion: kubeadm.k8s.io/v1beta3
kind: ClusterConfiguration
kubernetesVersion: v1.29.5
apiServer:
  extraArgs:
    service-node-port-range: 80-32767
networking:
  podSubnet: 10.0.0.0/16
controlPlaneEndpoint: 192.168.0.2:6443
---
apiVersion: kubelet.config.k8s.io/v1beta1
kind: KubeletConfiguration
serverTLSBootstrap: true
    